name: ICS to JSON
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # Prefer repository variable; allow secret override if you later move it to secrets
      ICS_URL: ${{ vars.ICS_URL }}
      REPO_VARIABLE: ${{ vars.REPO_VARIABLE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Generate JSON
        run: |
          echo "ICS_URL=${ICS_URL}"
          if [ -z "${ICS_URL}" ]; then
            echo "ICS_URL is empty. Ensure repository variable 'ICS_URL' is defined." >&2
            exit 1
          fi
            
          python -m src.main --ics-url "${ICS_URL}" --repo-variable "${REPO_VARIABLE}" --output events.json
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: events-json
          path: events.json
